name: Test Sed
on:
  push:
    branches:
      - main

jobs:
  test-sed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: step 1
        id: sed
        run: |
          out="$(cat test.txt)"
          out="${out//'%'/'%25'}" && out="${out//$'\n'/'%0A'}" && out="${out//$'\r'/'%0D'}" && \
          out="$(echo $out | sed 's|Refreshing state.||g')"
          out="$(echo $out | sed 's|\\e\[0m||g')"
          out="$(echo $out | sed 's|\\e\[1m||g')"
          out="$(echo $out | sed 's|\\e\[31m||g')"
          out="$(echo $out | sed 's|\\e\[32m||g')"
          out="$(echo $out | sed 's|\\e\[33m||g')"
          out="$(echo $out | sed 's|\\e\[90m||g')"
          out="$(echo $out | sed 's|\[.*\]:||g')"
          echo "::set-output name=plan::$out"
