name: Test Sed
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-sed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: step 1
        id: sed
        run: |
          # https://thekevinwang.com/2022/06/13/github-actions-survival-skills/
          # https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml
          out="$(cat test.txt)"
          out="${out//'%'/'%25'}" && out="${out//$'\n'/'%0A'}" && out="${out//$'\r'/'%0D'}" && \
          out="$(echo $out | sed 's|Refreshing state.||g')" && \
          out="$(echo $out | sed 's|\\e\[0m||g')" && \
          out="$(echo $out | sed 's|\\e\[1m||g')" && \
          out="$(echo $out | sed 's|\\e\[31m||g')" && \
          out="$(echo $out | sed 's|\\e\[32m||g')" && \
          out="$(echo $out | sed 's|\\e\[33m||g')" && \
          out="$(echo $out | sed 's|\\e\[90m||g')" && \
          out="$(echo $out | sed 's|\[.*\]:||g')"
          echo $out
          echo "::set-output name=plan::$out"

      - name: update pull request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            <details><summary>Show Plan</summary>

            \`\`\`
            ${{ steps.sed.outputs.plan }}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
